### ISSUE TITLE
Generic Fine Sun Sensors

### ISSUE THREAD

**Issue by jlucas9** [nasa/nos3#103]
Task breakdown:
- [X] Utilize the template component to create a baseline Fine Sun Sensor (CSS) repository in [nasa-itc](https://github.com/nasa-itc/generic_fss)
- [X] Define the commands and responses expected from the FSS and capture in the docs (icd)
- [x] Update readme to define commands and telemetry expected and format of all communications
- [x] Review readme with NOS3 CCB
~- [ ] Code checkout application~
- [x] Code hardware simulator
~- [ ] Test checkout application and hardware simulator~
- [x] Code cFS application
- [x] Create ground software cmd / tlm
- [x] Test cFS application, ground software cmd / tlm, and hardware simulator
~- [ ] Ground software test runner~

Protocol: SPI
MSGID range: 0x1920 - 0x1921
Note that it is assumed telemetry messages are also within range without the 0x1XXX indicating a command.

**Comment by msuder** [comment]
All code has been merged into dev.  This issue can be closed.
