### ISSUE TITLE
User Improvements

### ISSUE THREAD

**Issue by jlucas9** [nasa/nos3#112]
Request to have the following installed by default:
* Ubuntu
- [x] Desktop scripts
- [x] Task bar
* Rocky Linux
- [x] Desktop scripts
- [x] Task bar

**Comment by jlucas9** [comment]
@msuder should we tackle this also before the next base box release?

**Comment by msuder** [comment]
Yes, I think so... I'm not a fan of the current baseboxes not having these things.

**Comment by msuder** [comment]
Worked in this issue:
https://github.com/nasa/nos3/issues/116
and this commit:
https://github.com/nasa-itc/deployment/commit/0ebd8d4668c7e320e405717e4278af16eabf4779

**Comment by msuder** [comment]
This was closed by merge, commits:
https://github.com/nasa-itc/deployment/commit/2a0d258c2f8462cc8c6ab21b582ef57d3e55b7de
https://github.com/nasa/nos3/commit/a285150cc2d282c39ee6a2b0cf52d3ea3e656a21
