### ISSUE TITLE
Deployment 202302

### ISSUE THREAD

**Issue by jlucas9** [nasa/nos3#116]
Updates to deployments to latest boxes and versions for VirtualBox and Vagrant from 202302.

**Comment by jlucas9** [comment]
COSMOS installation error may be linked to [an existing rubygems issue](https://github.com/rubygems/rubygems/issues/6197)

**Comment by jlucas9** [comment]
Output from bentu/Ubuntu20.04 -v 202212.11.0 box:

TASK [nos3-ground : Install cosmos gem] ****************************************
Tuesday 24 January 2023  15:10:11 +0000 (0:00:01.839)       0:09:41.441 *******
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "gem install cosmos -v 4.5.2 --no-document", "delta": "0:00:01.303076", "end": "2023-01-24 15:10:13.171829", "msg": "non-zero return code", "rc": 1, "start": "2023-01-24 15:10:11.868753", "stderr": "ERROR:  Error installing cosmos:\n\tThe last version of bundler (>= 1.3) to support your Ruby & RubyGems was 2.3.26. Try installing it with `gem install bundler -v 2.3.26` and then running the current command again\n\tbundler requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.", "stderr_lines": ["ERROR:  Error installing cosmos:", "\tThe last version of bundler (>= 1.3) to support your Ruby & RubyGems was 2.3.26. Try installing it with `gem install bundler -v 2.3.26` and then running the current command again", "\tbundler requires Ruby version >= 2.6.0. The current ruby version is 2.5.0."], "stdout": "", "stdout_lines": []}

**Comment by msuder** [comment]
This was closed by merge, commits:  
https://github.com/nasa-itc/deployment/commit/2a0d258c2f8462cc8c6ab21b582ef57d3e55b7de
https://github.com/nasa/nos3/commit/a285150cc2d282c39ee6a2b0cf52d3ea3e656a21
