### ISSUE TITLE
SimTerminal - Multiple NOS Engine Support

### ISSUE THREAD

**Issue by msuder** [nasa/nos3#123]
- [x] Add the ability for SimTerminal to connect to multiple NOS Engine Servers (potentially on different hosts)
- [x] Add the ability for SimTerminal to switch between which NOS Engine Server the terminal currently has its bus/node to command connected to.
- [ ] #149
- [ ] How to broadcast a message to different sims across multiple engines? (if this is needed)

**Comment by jlucas9** [comment]
Merged to `dev` and created two new issues to track other features.
