### ISSUE TITLE
gsw/scripts/*.sh - Set executable bit in git

### ISSUE THREAD

**Issue by msuder** [nasa/nos3#129]
The shell scripts in gsw/scripts/*.sh are not executable by default when you fetch them from git.

https://stackoverflow.com/questions/46175753/how-do-i-see-the-permission-of-a-file-in-git#:~:text=Use%20git%20ls%2Dfiles%20%2Ds,ever%20see%20644%20or%20755.

https://medium.com/@akash1233/change-file-permissions-when-working-with-git-repos-on-windows-ea22e34d5cee

**Comment by jlucas9** [comment]
Main or `dev` branch? Should be resolved in commit 6686c03122abfac4d53d4261c07bc30c3241d79d

**Comment by msuder** [comment]
This has been implemented and tested.  This issue can be closed.
