### ISSUE TITLE
Rework "components" build system style to move flight software CMakeLists.txt files into fsw/ subdirectories

### ISSUE THREAD

**Issue by msuder** [nasa/nos3#134]
It is confusing (and unnecessary) for all NOS3 components to have the top level CMakeLists.txt file really only be applicable to flight software.  These should be moved down a level in each submodule repository with (potential) adjustments needing made to the flight software build system (especially under fsw/nos3_defs).

**Comment by jlucas9** [comment]
Merged into `dev`!
