### ISSUE TITLE
With multiple NOS3 SC VMs running:  Start/stop FSW/Sims/42 All SC at Once

### ISSUE THREAD

**Issue by msuder** [nasa/nos3#139]
One low hanging fruit implementation:
Build a shell script that uses ssh into each SC VM and runs "make launch" or "make stop"
(Design question:  how does the script "discover" the multiple NOS3 SC VMs? - hardcoded, smarter?)

**Comment by jlucas9** [comment]
Closed as part of merge https://github.com/nasa/nos3/commit/b5a51c34c1219ba4463c304ffd3099c39ebc5db1
