### ISSUE TITLE
Start/stop multiple NOS3 SC and Common VMs

### ISSUE THREAD

**Issue by msuder** [nasa/nos3#140]
Vagrant up? (and Vagrant halt?) for Multiple NOS3 SC and Common VMs
Or maybe some alternative to Vagrant.
(Design question: how does the script "discover" the multiple NOS3 SC VMs? - hardcoded, smarter?)

**Comment by jlucas9** [comment]
Closed as part of merge https://github.com/nasa/nos3/commit/b5a51c34c1219ba4463c304ffd3099c39ebc5db1
