### ISSUE TITLE
Get Checkout Apps to Build and Run with hwlib Simulator .c code

### ISSUE THREAD

**Issue by msuder** [nasa/nos3#146]
Currently checkout application code for components is untestable with real hardware because there is none.

This code is untestable with the simulator because of issues building with the simulator hwlib (but it is not required for testing the sim... the sim can be tested with fsw, the sim terminal, or by other means... so it is not high priority to fix this).

Figure out issues with building (compiling/linking) and running against nos3/fsw/hwlib/sim/src code.

**Comment by jlucas9** [comment]
Merged into `dev`
