### ISSUE TITLE
SimTerm - Protocol Configuration

### ISSUE THREAD

**Issue by jlucas9** [nasa/nos3#149]
Sim Terminal should not be setting the protocol in use by referencing the name, but should instead have a specific configuration field that can be set.

**Comment by msuder** [comment]
This was already fixed in commit:
https://github.com/nasa-itc/sim_terminal/commit/92cffd63628d3e2cda1c68b81cb55576e427126b
for issue:
https://github.com/nasa/nos3/issues/123

**Comment by msuder** [comment]
Opened separate issue https://github.com/nasa/nos3/issues/153 to add slave connections for CAN/I2C/SPI.

**Comment by msuder** [comment]
Wrote issue https://github.com/nasa/nos3/issues/154 for exception thrown/SimTerminal quitting when switching to uart bus type.

**Comment by msuder** [comment]
Tested UART connection to GPS sim - works.
Tested I2C connection to CSS sim - works.
Tested SPI connection to FSS sim - works.
