### ISSUE TITLE
Install issues Vagrant up fails

### ISSUE THREAD

**Issue by shaynababe** [nasa/nos3#167]
(base) z@spin7:~/code/nos3$ vagrant up
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: Unable to resolve dependency: 'puppet_forge (>= 2.1)' requires 'minitar (>= 0)'
(base) z@spin7:~/code/nos3$ 

tried to purge and reinstall not good This is typical of this config I admit not doing the GPG keys and wget for this install 
sudo apt 
```bash
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
**sudo apt update && sudo apt install vagrant**

**Comment by jlucas9** [comment]
What is your host OS? 
NOS3 should not require any vagrant plugins - Could your Vagrant and VirtualBox versions on your host be mismatched?

**Comment by jlucas9** [comment]
Attempting to recreate the issue:
* Downloaded Debain Bookworm ISO
  * From https://cdimage.debian.org/cdimage/bookworm_di_alpha1/amd64/iso-cd/
* Created new VM and installed ISO
  - 8 core, 32GB, 40GB HDD, Enable Nested VT-x/AMD-V
  - Installed Guest Additions since using VM to test
    * sudo apt update
    * sudo apt install build-essential dkms linux-headers-$(uname -r)
    * sudo reboot now
* Install dependencies
  - Add unstable "Sid" to `/etc/apt/sources.list`
    * `deb http://deb.debian.org/debian/ sid main contrib non-free`
  - sudo apt update
  - sudo apt install curl git virtualbox 
  - sudo apt install virtualbox-ext-pack
  - curl -O https://releases.hashicorp.com/vagrant/2.3.4/vagrant_2.3.4-1_amd64.deb
  - sudo apt install ./vagrant_2.3.4-1_amd64.deb
* Clone NOS3 and create VM
  - git clone https://github.com/nasa/nos3.git
  - cd nos3
  - git submodule update --init --recursive
  - vagrant up
    * No reported error, VM launched

Did your installation steps deviate from the above or have any other error logs you could provide to recreate the issue?

**Comment by shaynababe** [comment]
let me try this

**Comment by shaynababe** [comment]
No the only install thats has  a working install is;
https://packages.debian.org/stretch-backports/virtualbox-ext-pack
https://packages.debian.org/sid/misc/virtualbox-ext-pack
The install has been purged now

**Comment by jlucas9** [comment]
Can you skip the `sudo apt install virtualbox-ext-pack`  and see if that process worked? I may have only needed that again because I was already in a virtualbox to perform the steps.

**Comment by shaynababe** [comment]
This is the vagrant error is want to add to the machine which prompted the issue

This is the issue
**Remote Desktop Protocol,** USB 2.0, PXE booting for Intel network cards, etc. This PUEL-licensed extension pack is free for personal use.

**Comment by jlucas9** [comment]
Hi @shaynababe, I've pushed a yet unofficial version 1.6.1 of the base box without remote desktop protocol enabled. Could you update your NOS3 Vagrantfile to this version and see if that gets you any further?

**Comment by shaynababe** [comment]
ok will try and report thanks

**Comment by shaynababe** [comment]
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
```bash
[tree.txt](https://github.com/nasa/nos3/files/11448210/tree.txt)

**Comment by jlucas9** [comment]
Closing for now due to age, if this continues to be an issue or interest please re-open or file a new one!
