### ISSUE TITLE
Component CI Pipeline

### ISSUE THREAD

**Issue by jlucas9** [nasa/nos3#216]
Can leverage examples from https://github.com/nasa/sample_app

Will need to update our component sample app.

**Comment by Isgaroth-the-Green** [comment]
I believe the next step is to check that the sample_app works within cFS and then compare it to the sample in NOS3 (at which point the CI tests in sample_app can be leveraged); I have not been able to get cFS compiling properly, though. It always gives an error regarding stubs, approximately
`/usr/bin/ld: cannot find -lut_core_api_stubs: No such file or directory`
and 
`/usr/bin/ld: cannot find -lcoverage-sample_lib-stubs: No such file or directory`
The command (I think) which gives this error is
`/usr/bin/cc -g CMakeFiles/coverage-sample_app-sample_app_uitls-testrunner.dir/coveragetest/coveragetest_sample_app_utils.c.o CMakeFiles/coverage-sample_app-sample_app_utils-object.dir/home/jstar/Documents/code/cFS/apps/sample_app/fsw/src/sample_app_utils.c.o -o coverage-sample_app-sample_app_utils-testrunner -pg --coverage -lut_core_api_stubs ../../../osal/ut_assert/libut_assert.a -lcoverage-sample_lib-stubs libcoverage-sample_app-stubs.a libcoverage-sample_app-stubs.a libsample_app_ut_common.a ../../../osal/ut_assert/libut_assert.a ../../../osal/libosal_bsp.a -lpthread -ldl -lrt`

**Comment by jlucas9** [comment]
Opted to just do NOS3 level CI and not with each component individually. So when you commit to the top level of NOS3 with the new component submodule it'll kick off, but not before then.

**Comment by jlucas9** [comment]
Merged and squashed to `dev`
