### ISSUE TITLE
Incorrect length in COSMOS dictionaries

### ISSUE THREAD

**Issue by fhough** [nasa/nos3#217]
Incorrect CCSDS length for the following commands. The command length is not being checked in their components. 

GENERIC_RADIO_CMD.txt - GENERIC_RADIO_REQ_HK
GENERIC_CSS_CMD.txt - GENERIC_CSS_REQ_HK, GENERIC_CSS_REQ_DATA
GENERIC_EPS_CMD.txt - GENERIC_EPS_REQ_HK
GENERIC_FSS_CMD - GENERIC_FSS_REQ_HK, GENERIC_FSS_REQ_DATA
GENERIC_IMU_CMD.txt - GENERIC_IMU_REQ_HK, GENERIC_IMU_REQ_DATA
SAMPLE_CMD.txt - SAMPLE_REQ_HK, SAMPLE_REQ_DATA

The current length for these commands is 0, when the length is actually 1.

**Comment by jlucas9** [comment]
Merged to `dev` in submodules and top level NOS3 repo.
