### ISSUE TITLE
This is more of a question.

### ISSUE THREAD

**Issue by bapichulo** [nasa/nos3#22]
So I have finished installing everything. I thought I had some issued because I didn't see the Nos3 target but after reading through this forum, I believe this is the way it is supposed to be.

I am just not completely sure how to use this software. This extends to how to send commands to the simulator, and if I can change the orbit, change the attitude, change the spacecraft itself, etc. Does anyone have explicit directions on how to do this? I'm currently using this software for my internship and the user manual is a little confusing to me.

**Comment by jlucas9** [comment]
Hi bapichulo,  

An updated version is currently in work and I'll be sure to expand the user's guide to include this info.  In short the 42 configuration files are on the desktop under the `42-InOut` folder.  Also note that the package that is included now is no-where near the latest open source 42 version.  In the next release, we will be using the latest (or close to) version.   

Typically the cFS component applications will communicate to the NOS Engine (simulating physical interfaces) via a hardware library.  NOS Engine then routes the commands to the appropriate simulator.  To trigger faults in the simulators we have the `sim_terminal` although I am not sure we included examples on this.  

If you have more questions feel free to post here or email support and we'll get back to you as fast as we can!
