### ISSUE TITLE
Wiki Update for Docker

### ISSUE THREAD

**Issue by jlucas9** [nasa/nos3#230]
Update the wiki documentation to be specific to docker in preparation for the next release.

**Comment by kevincbruce** [comment]
Cloned Branch nos3#230-wiki-update-for-docker to work on this issue and Igniter Documentation.

**Comment by rjbrown2** [comment]
On the Wiki front page, there are some link naming mismatches:
Navigation links in the middle of the page do not match the naming on the right side bar.  For example: Architecture vs NOS3 Architecture.  They are close enough to not cause confusion, but they should probably match.

**Comment by jlucas9** [comment]
Can we also resolve https://github.com/nasa/nos3/issues/136 as part of this effort?

**Comment by kevincbruce** [comment]
> On the Wiki front page, there are some link naming mismatches: Navigation links in the middle of the page do not match the naming on the right side bar. For example: Architecture vs NOS3 Architecture. They are close enough to not cause confusion, but they should probably match.

Should have fixed that. Those were how the names originally were before I made edits, but should match now.

**Comment by kevincbruce** [comment]
Addressed most of #136 today, so that is ready for review.

**Comment by kevincbruce** [comment]
Finished addressing #136 (both in code and in documentations), and fixed the description and pictures of enabling TO for Radio. Starting Architecture updates tomorrow afternoon.

**Comment by kevincbruce** [comment]
There is a fair bit of copy and paste, but I updated the Ground Software wiki to reflect the two ground systems, show Radio TO setup on both, and show how to use the Master Config to toggle them

**Comment by jlucas9** [comment]
Closing in favor of new issues as things continue to be updated
