### ISSUE TITLE
Vagrant update

### ISSUE THREAD

**Issue by Isgaroth-the-Green** [nasa/nos3#247]
With the configuration changes the most recent version of Vagrant does not work. Vagrant 2.4.0 gives an error pertaining to the version number, as shown in [this image](https://nasa.sharepoint.com/:i:/r/teams/JSTARInternal/Shared%20Documents/Small%20Satellites/Screenshot%202024-01-04%20170002.png?csf=1&web=1&e=mYxU9o). 

Essentially, Vagrant says that the requested version (20231101 at time of this writing) is unavailable, but then lists 20231101 as an option in the list of versions. This error does not present itself with Vagrant 2.3.4 but does with 2.4.0; Vagrant versions between those two have not been checked.

**Comment by jlucas9** [comment]
Confirmed that the latest vagrant version 2.4.1 works! Recommend all upgrade if they run into this issue.
