### ISSUE TITLE
Wiki Updates

### ISSUE THREAD

**Issue by bjkowalski** [nasa/nos3#278]
Edit comments on Wiki page [NOS3-Igniter](https://github.com/nasa/nos3/wiki/NOS3-Igniter) indicate that the Wiki information was added back on Feb 29.  My searches through the NOS3 GIT "dev" repo have not identified any executable with "igniter" in a source code file name nor are there any instructions on how to launch or download and create this utility.

I discovered the branch "234-nos3-igniter" was created to support the igniter development work.  One shortcoming of using the GITHUB Wiki is that there is no parallel to the branch capability of the repo.  Changes to the Wiki are viewable by everyone without branch qualification.  So while I commend the author for proactively adding the documentation, it may cause some confusion for folks who are not familar with the team development practices.

I'd like to propose that when updates are added to the Wiki information that may be only applicable to a specific branch that there is an indication in those updates that they only apply to the specific branch identified.  For instance, at the top of the [NOS3-Igniter](https://github.com/nasa/nos3/wiki/NOS3-Igniter) Wiki page a comment could be added in bold that says

> **The information on this page is only applicable to the "234-nos3-igniter" branch**

**Comment by Donnie-Ice** [comment]
Igniter is now part of the dev branch and the wiki has been updated to reflect the current status of Igniter (pictures were not updated).
