### ISSUE TITLE
FSW Organization for Fprime and cFS

### ISSUE THREAD

**Issue by zlynch2** [nasa/nos3#295]
reconfigure nos3 fsw/ directory to handle both cFS and Fprime. So under fsw/ we have cFS/ and fprime/

Also, will need to reconfigure the componenet directory to be the same. for example sample/fsw/cFS and sample/fsw/fprime

**Comment by jlucas9** [comment]
Ready for testing @zlynch2 / @rjbrown2 - note this was created off your fprime branch

**Comment by zlynch2** [comment]
Merged branch into nos3#84-fprime-checkout
