### ISSUE TITLE
Login invalid?

### ISSUE THREAD

**Issue by cscase** [nasa/nos3#3]
I ran the provisioning process as described in the readme. It did take a fair while, about 30 minutes, and afterward, it started the VM. I've shut it down and restarted it a couple of times, but always come to the same place. I get a console-looking screen like this:
![image](https://user-images.githubusercontent.com/10687071/46251598-9738a380-c41c-11e8-9c7e-41e7c5877299.png)

I am entering user name: nos3
Password: nos3123!
Here's what I get in the console when starting the VM:
![image](https://user-images.githubusercontent.com/10687071/46251605-b6cfcc00-c41c-11e8-85df-c66b3ee856d4.png)

If I understood the directions correctly, I would have expected the VM to boot to a desktop type Ubuntu environment, and that's not happening.

Where am I going wrong?

Thanks!
Scott

**Comment by cscase** [comment]
I think somehow when I ran this, the provisioning process didn't actually complete. When it works right, it should boot into a full desktop type environment. I think in this case I needed to delete the VM and just restart the process. Seems like it's doing better.

**Comment by lipofefeyt** [comment]
Is someone else experiencing this issue? Because I can't actually get pass this... Thanks!

**Comment by jlucas9** [comment]
Hi @lipofefeyt ,  
Provisioning from scratch can take a very long time and is not guaranteed to succeed. Due to this we have added OVAs to the release that can simply be downloaded and imported into Virtual Box directly without the need for Vagrant at all.  You can find the releases [here](https://github.com/nasa/nos3/releases).  
Have a great day!

**Comment by lipofefeyt** [comment]
Hi @jlucas9,

Thanks for the quick answer. I will try it and come back to you ASAP.

Cheers!
