### ISSUE TITLE
EPS -  battery voltage behavior

### ISSUE THREAD

**Issue by Simon9050** [nasa/nos3#305]
Hi, 

I am using the dev branch of the EPS component and I am surprised by the following behavior of the battery voltage when passing to the eclipse phase :  

![Picture1](https://github.com/nasa/nos3/assets/161499474/f3a65304-aad6-4e27-be74-fd9cbe21d7ad)

is it normal ? 

moreover, if I select one of the switch to be ON, I cannot see any impact on the battery voltage... what am I missing ? 

Thank you for your help, 

Best Regards,  

Simon

**Comment by Isgaroth-the-Green** [comment]
Simon,

regarding the voltage during the eclipse phase, I would expect to see it drop (though probably not quite that precipitously); how long is the satellite eclipsed in your simulation? That is, is the voltage dropping for all of the time the satellite is eclipsed, or only for a portion of that time?

As for the switches impacting the voltage, are you saying there was no instantaneous change, or that the change over time of the voltage was not impacted by turning on one of the switches? I would expect there to be no instantaneous change with the way the voltage and switches are being modeled, but if you are saying that there was no impact on the voltage over time, that would be more surprising. Also, which switch was it?

**Comment by Simon9050** [comment]
Hi! Thank you for your reply, 

I think the problem is not related to the eclipse phase as I have the same behavior during a standard simulation (and battery voltage is oscillating every 4 min...). I think there is an issue with my code, but I was not able to find the origin of this strange behavior. 
For the switch, I have tried the number 1 and I was not able to see a clear difference over time on the voltage. 
Could you please share some plot of EPS normal behavior ? 
Thank you again for your support. 
Simon

![err_eps](https://github.com/nasa/nos3/assets/161499474/b5417e9e-90cc-4385-924a-8175d365741e)
![err-eps2](https://github.com/nasa/nos3/assets/161499474/dd29e288-703d-4548-a4c9-0687a46cab90)

**Comment by Isgaroth-the-Green** [comment]
Simon,

when I run the current dev branch, I get a very slowly decreasing battery voltage but no oscillations the way you are describing (I ran it for twenty minutes to be sure). What branch are you running? My first thought is that you are getting overflow errors because the battery voltage is being set wrong; its value is contained in a uint16_t, which goes from 0 to 65535, and measures mV (so that would correspond to where the change is happening). Also, what is the output of the NOS3 FSW terminal (the one which launches in a separate window) when you try to command a change to one of the switches?

**Comment by Simon9050** [comment]
Hi! and thank you again for your support 

I am running the main branch and I have added the dev branch modifications only for the EPS component as I was interested in simulating the battery draining. 
Your thought is correct, I have overflow errors on the battery voltage... I was not able to debug my code for now, but I think the problem is related to the sun_vector computation, as I can see that it is not a unit vector and I have very high values on the p_in...  are there specific modifications for 42 code (or other interacting components) that I am missing ? 

For the switches I have the following messages on the FSW terminal that I suppose are ok : 
![Untitled33](https://github.com/nasa/nos3/assets/161499474/80dddd9a-d0fa-4c42-87b6-efe53f949ebf)

**Comment by Isgaroth-the-Green** [comment]
Simon,

of course - glad to be of assistance.

I presume that you are not running the most version of main; we pushed a new release to main pretty recently. What is the order of magnitude of the p_in values? I would expect them to be between 0 and 20; it sounds like they are substantially different from that for you. Do you need to be running the older version of main? And if not, could you try with the newer code and see if that solves the problem?

**Comment by Simon9050** [comment]
Hi, 
I have tested the last version of NOS3 and I can confirm that EPS values are plausible. I will try to use the new version. 
Thanks,
Have a nice day!
