### ISSUE TITLE
COSMOS4 problem when closing windows

### ISSUE THREAD

**Issue by Gonta01** [nasa/nos3#312]
When I close any window in COMSOS4 the following window pops up:
![image](https://github.com/nasa/nos3/assets/127857320/f14e517c-653b-4d33-be08-14b38b72ba05)

**Comment by Isgaroth-the-Green** [comment]
Good morning.

I have experienced the same thing as you, but as far as our team can tell it does not have any deleterious effects. You should be able to simply click "OK" or close the window and continue using NOS3. 

Also, this is the version of COSMOS we typically use; COSMOS5 adds quite a bit of overhead.

**Comment by jlucas9** [comment]
@Gonta01, can you try `dos2unix ./generate_template.sh` and see if that resolves it for you?

**Comment by Gonta01** [comment]
@jlucas9 I configured VSCode so that end of line sequence is LF not CRLF inside files, so I don't encounter problem neither with COSMOS4 nor with generate_template.sh.
