### ISSUE TITLE
Custom simulator exits

### ISSUE THREAD

**Issue by Gonta01** [nasa/nos3#321]
Created custom simulator (hardware model) but it exits at the very beginning so that I could not even see logs.
Could somebody give debugging tips for this situation?

**Comment by jlucas9** [comment]
Hi @Gonta01, can you confirm that your hardware model key is in the configuration file being used?

Looking at the default sample sim output for example:
![image](https://github.com/nasa/nos3/assets/6588622/69033a0b-127b-4791-bd2d-a5de06fc12ad)

The sample simulator contains the same <hardware-model> / <type> key that is listed in the printed configuration it read - https://github.com/nasa-itc/sample/blob/dev/sim/src/sample_hardware_model.cpp#L5

If I change the following:
* sample_hardware_model.cpp line 5
  * `REGISTER_HARDWARE_MODEL(SampleHardwareModel,"SAMPLE_ERROR");`
* docker_launch.sh line 130
  * `    gnome-terminal --window-with-profile=KeepOpen --title=$SC_NUM" - Sample Sim"   -- $DFLAGS -v $SIM_DIR:$SIM_DIR --name $SC_NUM"_sample_sim"   --network=$SC_NETNAME -w $SIM_BIN $DBOX ./nos3-single-simulator $SC_CFG_FILE sample_sim`
  * Assuming the KeepOpen profile exists in gnome-terminal as you [linked](https://github.com/nasa/nos3/issues/260#issuecomment-1971126479)

![image](https://github.com/nasa/nos3/assets/6588622/db6deb39-4f39-4b73-b14d-5e8c74ef5cd7)

Let me know if things still aren't working for you and I can take a further look!

**Comment by Gonta01** [comment]
@jlucas9 thank you for your response! In my case names are the same. 
I have looked through logs of Sim more carefully and found the following message:
![image](https://github.com/nasa/nos3/assets/127857320/288db072-a6e0-47e6-8ae8-252be5ad7407)

Trying to find out why is it happening.

**Comment by Gonta01** [comment]
I created my own application STS21 on the basis of Sample and after this tried to use I2C instead of UART and probably some configurations are missed

**Comment by Gonta01** [comment]
I've found how to fix the [problem](https://github.com/nasa/nos3/issues/321#issuecomment-2179989758)
Instead of uart I should write i2c and this problem doesn't occur again
![image](https://github.com/nasa/nos3/assets/127857320/5519135b-7c3a-42e1-a627-b4f1dc596484)

**Comment by Gonta01** [comment]
@jlucas9 thank you again.
In my opinion this particular issue is solved.
