### ISSUE TITLE
COSMOS receives error messages

### ISSUE THREAD

**Issue by Gonta01** [nasa/nos3#322]
Added new component and seems to resolve all troubles related to it (including [issue](https://github.com/nasa/nos3/issues/321))
Some problem remain but I'm not sure what could cause it. Just after the start of the system and activating of COSMOS, COSMOS receives the following messages:
![image](https://github.com/nasa/nos3/assets/127857320/8cedaf17-8b1d-4154-80a5-fbd09e46cfee)

Where could be hidden the problem and how to debug it?

**Comment by Gonta01** [comment]
In Tlm packets found the following:
![image](https://github.com/nasa/nos3/assets/127857320/4a1a8cc4-b70a-4ce7-9fb5-793f266cd6dd)

There is UNKNOWN target and my newly added component(STS21). Probably they are not related.

**Comment by Gonta01** [comment]
I has found that Software Bus task houskeeping Packet starts with 0x0803
![image](https://github.com/nasa/nos3/assets/127857320/82ec7d22-f6bf-4825-974a-09b69f64536b)

**Comment by Gonta01** [comment]
Compared CFS and CFS_RADIO targets.
![image](https://github.com/nasa/nos3/assets/127857320/72f80568-958b-4887-bd69-2ced7e99ee2f)
![image](https://github.com/nasa/nos3/assets/127857320/e33a09ec-76b9-4808-84d1-cb7520dc79f8)

It seems that CFE_SB_HKMSG, CFE_SB_PREVSUBMSG, CFE_SB_STATMSG and CFE_SB_SUBPRTMSG in case of CFS target (not CFS_RADIO) for some reason are labeled as UNKNOWN and somehow influence CFE_TBL_HKPACKET based on logs:
![image](https://github.com/nasa/nos3/assets/127857320/720b7592-1112-4cca-92e2-8ac848362b38)

**Comment by Gonta01** [comment]
In cmd_tlm_server.txt and system.txt of gsw commented RADIO target of STS21 and problem SEEMS to be fixed:
![image](https://github.com/nasa/nos3/assets/127857320/ad454ca2-1daf-4835-b1d5-3a901b4d25b6)
![image](https://github.com/nasa/nos3/assets/127857320/0f65dbef-795e-4e9f-8a83-256c2312d9ff)

CFE_SB_HKMSG, CFE_SB_PREVSUBMSG, CFE_SB_STATMSG and CFE_SB_SUBPRTMSG appeared in CFS target:
![image](https://github.com/nasa/nos3/assets/127857320/f5bb1794-c4d8-4a66-b766-241cf4083bbe)

Are there any limitations of targets for this ground station (COSMOS 4)?

**Comment by kevincbruce** [comment]
Hello @Gonta01, I hope you're well! Did you add a COSMOS Dictionary for your app? They'd be found in nos3/gsw/cosmos/COMPONENTS. You'd add a directory with all the equivalent stuff to what's there for other apps for your app, and define your packets in the way found in the other dictionaries. That way, COSMOS recognizes your APP_ID, MIDs, CCs, etc. correctly, and knows what lengths to look for and what values to put where. Should also make it show up in the packet viewer and  command sender and the like. If you've already done it, is there a misconfiguration/misplaced file, or a formatting error within one of those files? Hope that helps!

**Comment by Gonta01** [comment]
Hi @kevincbruce. I have uncommented [STS21_RADIO components](https://github.com/nasa/nos3/issues/322#issuecomment-2182123621), built again and it seems to be everything good for now.
Have no idea what was the root of the problem and how it was fixed.

**Comment by jlucas9** [comment]
@Gonta01 this could have been related to MSGIDs clashing. It appears that CFE_SB_HK_TLM_MID is also 0x0803 - https://github.com/nasa/nos3/blob/dev/cfg/nos3_defs/cpu1_msgids.h#L118

**Comment by Gonta01** [comment]
Newly added component had and has unique MSGIDs:
STS21_CMD_MID              0x18A0
STS21_REQ_HK_MID           0x18A1

Nevertheless, for now issue was somehow fixed (by disabling new component, and further enabling and building?). In case, if this problem appears again, I'll let you know and reopen this issue.
