### ISSUE TITLE
nos3 login

### ISSUE THREAD

**Issue by goalomy** [nasa/nos3#33]
![VirtualBox_NOS3_Ubuntu_21_04_2020_16_58_34](https://user-images.githubusercontent.com/63917677/79861490-1a9c5a00-83f2-11ea-8b8a-8c173177f89f.png)

unable to enter nos3 login and password.What i need to do please suggest the way.

**Comment by Abhishek5101** [comment]
The root username is vagrant and password is vagrant

**Comment by PeteBlanchard** [comment]
It appears that your build may have run into difficulty...

I am not an expert on it, but when I do my vagrant builds, if I am behind a corporate firewall that re-writes certificates, I have to update the local certificate store with the company 'trusted' cert authority...I also export a couple environment variables for other tools that use ssl to work properly (in the /etc/bash.bashrc)
```bash
export CURL_CA_BUNDLE=/etc/ssl/certs
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
```

After you do that, you may need to re-run the build scripts
