### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by gardinwin** [nasa/nos3#350]
Hi.

After starting the simulator, the memory usage decreases over time. 
Should the messages or resources received by the user be released? 
Or does the automatic garbage collector periodically release the resources?

Thanks.

**Comment by jlucas9** [comment]
Hi @gardinwin, 

Thanks for bringing this to our attention. After launching in my VM and getting to a steady sun pointed state (1026):

![image](https://github.com/user-attachments/assets/30a27857-a10a-457d-a457-678ebc00ef32)

I just let it run for awhile (1105) and memory use from 42 appears to continue to increase:

![image](https://github.com/user-attachments/assets/4d63e0b6-7c08-441c-a51f-08043cd52303)

I'll keep this issue open and continue to investigate to get this resolved.

**Comment by gardinwin** [comment]
Thanks your reply나의 iPhone에서 보냄2024. 8. 31. 00:06, John P. Lucas ***@***.***> 작성:﻿
Hi @gardinwin,
Thanks for bringing this to our attention. After launching in my VM and getting to a steady sun pointed state (1026):
image.png (view on web)
I just let it run for awhile (1105) and memory use from 42 appears to continue to increase:
image.png (view on web)
I'll keep this issue open and continue to investigate to get this resolved.

**Comment by msuder** [comment]
I ran 42 under valgrind (leakcheck).  None of the findings turned out to be a memory leak.

**Comment by msuder** [comment]
To run 42 under valgrind, you have to modify the docker container that runs 42.  This requires starting the container from an image, executing the commands in the container to install valgrind, and then saving the container as a new image.  This new image then needs used to run 42 under valgrind.

**Comment by msuder** [comment]
I redouble checked today with `valgrind --leak-check=full` and did not see any obvious memory leaks.

**Comment by msuder** [comment]
I ran the EPS nos3-single-simulator under valgrind (leakcheck) and it  showed no leaks.  I also watched htop and the simulators and  they were holding a constant amount of memory.  So the simulators are not leaking memory.

**Comment by msuder** [comment]
This issue is recommended for closure.
