### ISSUE TITLE
X-band downlink

### ISSUE THREAD

**Issue by gardinwin** [nasa/nos3#353]
Any samples about downlink for image ?

**Comment by jlucas9** [comment]
HI @gardinwin,
Sorry for the delay getting back to you. The arducam application / simulation does send a canned picture when requested. 

https://github.com/nasa-itc/arducam/blob/main/sim/src/cam.bin
Simply change the file type to .jpeg and that's the image used (from the actual STF-1 Arducam during testing).

Let us know if you're interested in getting a dynamically simulated image and we can try to work that in the roadmap moving forward. Have a great day!

**Comment by jlucas9** [comment]
Closing due to age - please reopen if still an issue!
