### ISSUE TITLE
Add clarifiers to software classifications

### ISSUE THREAD

**Issue by jlucas9** [nasa/nos3#356]
Need to be sure we address that NOS3 is really the architecture, it's own software classification as it's not flying, and the FSW classification and what you would fly.

https://swehb.nasa.gov/display/SWEHBVB/SWE-020+-+Software+Classification?desktop=true&macroName=report-body

**Comment by Isgaroth-the-Green** [comment]
Added some clarification [here](https://github.com/nasa/nos3/wiki); let me know if it is insufficient.

**Comment by jlucas9** [comment]
Looks good to me! Thanks!
https://github.com/nasa/nos3/wiki#how-is-nos3-classified
