### ISSUE TITLE
GSW Relaunch w/o Rebuild

### ISSUE THREAD

**Issue by jlucas9** [nasa/nos3#357]
When make real-clean and re-making things work fine. However If I make stop and make launch back to back. Cosmos doesn't seem to launch its Nos3 Launcher after clicking ok. Can others confirm.

_Originally posted by @zlynch2 in https://github.com/nasa/nos3/issues/355#issuecomment-2318877204_

**Comment by szemerick** [comment]
confirmed the same behavior on a fresh NOS3 while performing a release test.
