### ISSUE TITLE
max-connection-attemps set to 0 for the thruster model

### ISSUE THREAD

**Issue by xpromache** [nasa/nos3#365]
Is there any reason why max-connection-attemps is set to 0 for the thruster model while for all the others it is set to 30?

https://github.com/nasa/nos3/blob/4d653f2a3defea391019176064173e12a0d674eb/cfg/sims/nos3-simulator.xml#L446

On one instance for some reason the first connection does not succeed (connection refused) and the whole start of the simulator is blocked.

This is a general criticism I have of the current setup of the NOS3 simulator - it starts lots of containers and if one thing inside one container is not working, it is nearly impossible to spot what the problem might be.

**Comment by jlucas9** [comment]
Hi @xpromache,
Sorry for the delay getting back to you. I can confirm this was just an oversight on my part in the merge requests.  Resolved in the latest `dev` branch - https://github.com/nasa/nos3/blob/de3488fc942cb87dade1b56d73bb7cc73a0ce7d0/cfg/sims/nos3-simulator.xml#L446

Thanks and please feel free to post more issues as you run into that we may be able to help with!
