### ISSUE TITLE
YAMCS Studio Integration

### ISSUE THREAD

**Issue by jlucas9** [nasa/nos3#367]
Integrate YAMCS studio into NOS3 (if not already a part of initial YAMCS)

**Comment by rjbrown2** [comment]
YAMCS Studio Integration Instructions:
Obtain the tarball appropriate to your system.  Note that YAMCS Studio requires JRE for Java 11 or higher.
https://github.com/yamcs/yamcs-studio/releases

Extract the tarball to your system, and you can run then ./'Yamcs Studio'
The YAMCS studio User's Guide is a great resource for setting up these interfaces, and this is how the JSTAR team accomplished this.  
We've also created a custom OPI file for the SAMPLE application that will allow users to view how scripting works to connect buttons to commands and telemetry.

Users can create a new project within the Display Builder within YAMCS Studio, and then import JSTAR's NOS_SAMPLE_APP.opi
Select the OPI file, and click the green play button to advance to the Display Runner (This will bring up the NOS Sample App OPI window)
From the Options ribbon at the top, select YAMCS, and then Connect.  (This assumes you already have NOS3 and the YAMCS Web gui running, functional, and receiving telemetry).
![image](https://github.com/user-attachments/assets/6db3b5fa-c0a0-46a2-8a26-6a9f00e27fe3)

Following successful connection, users should be able to run the Enable_CC command from the sample app OPI, and begin seeing telemetry:
![image](https://github.com/user-attachments/assets/2e4ca94d-4dc9-4b32-8d13-c4361622c0cb)

The OPI File will be uploaded as part of the #80 upcoming merge into dev.

**Comment by rjbrown2** [comment]
OPI File lives within:
gsw/yamcs-studio/  Under the NOS3 root directory.
