### ISSUE TITLE
NOS Engine User’s Manual

### ISSUE THREAD

**Issue by PeteBlanchard** [nasa/nos3#37]
Was reading the [NOS3 User's Manual](https://www.stf1.com/NOS3Website/docs/NOS3_CombinedDocumentation.pdf) which (on page 9) refer's to the NOS Engine User's Manual, but I have not been able to find it...

Where is it located?

Thanks in advance.

**Comment by mgrubb-gsfc** [comment]
It is under documents on the NOS3.org site. http://www.stf1.com/NOS3Website/docs/20170120_TESS_TO9_NOSEngineUsersGuide_v01.pdf

**Comment by PeteBlanchard** [comment]
thanks...btw, also found an older one linked off the 1_04_00 'releases' page of github. (https://github.com/nasa/nos3/releases; 20160107_NOSEngineUsersGuide_Public.pdf). I missed seeing that before.
