### ISSUE TITLE
fprime merge cleanup from nos3#84

### ISSUE THREAD

**Issue by zlynch2** [nasa/nos3#376]
- [x] Review Star tracker config (uart number) in nos3-simulator.xml.
- [x] Test 42 provider with star tracker, in nos3-simulator.xml
- [x] Should we have a single launch script and then calls the various pieces based on configuration instead of two separate ones to manage? (cfs_cosmos.sh)
- [x] docker_debu.sh, need to review and make docker debug. ports needed for fprime?
- [x] Configure.py, Should we overwrite the ./scripts directory or move this into the hidden ~/.nos3 or a build directory and run it out of there like we do for GSW?
- [x] Docker_checkout.sh, need multiple docker checkouts depending on FSW running fprime, cfs, etc.
- [x] F' gds running direct in terminal changed to its own, and fprime fsw launching in its separate terminal

**Comment by zlynch2** [comment]
merge from @jlucas9 feature branch fixed f' gds and f' fsw launching in own windows.

**Comment by jsilveira1409** [comment]
hi @zlynch2 ! i would love to contribute to this integration of fprime with nos3, let me know how I can help

**Comment by zlynch2** [comment]
hi @jsilveira1409 that would be awesome, first we would need you to return some paper work in order for you to get started. Ill have @jlucas9 get that to you.

**Comment by zlynch2** [comment]
Acutally @jsilveira1409 looks like you can find what you need here: 
https://github.com/nasa/nos3?tab=readme-ov-file#contributions

Follow those steps, and you can start contributing to fprime work

**Comment by zlynch2** [comment]
Star tracker is being fixed with correct uart in #351

**Comment by zlynch2** [comment]
Docker checkout will be added to development roadmap

**Comment by zlynch2** [comment]
Closing issue, above issues tracked and committed in other issues. Uart 10 fixes star tracker, and 42 provider
