### ISSUE TITLE
F' data produced on a schedule

### ISSUE THREAD

**Issue by jlucas9** [nasa/nos3#384]
Part of the F' integration effort. Looking to use F' to produce data on a set schedule - collect sample data at 1Hz and publish it.

**Comment by zlynch2** [comment]
last commit has sample sending data at 1 hz 20 times. Will not run indefinitely due to bug with sequence cancel command. May create separate issue for canceling the sequence.

**Comment by zlynch2** [comment]
This was closed with merge of nos3#384 branch into dev
