### ISSUE TITLE
Bad Link on Website (https://www.stf1.com/NOS3Website/Nos3DocumentationTab.html)

### ISSUE THREAD

**Issue by PeteBlanchard** [nasa/nos3#39]
FYSA,

On the Nos3DocumentationTab.html, in the navigation tab on the right, the 'Directory structure' link under 'Getting Started' points to "https://www.stf1.com/NOS3Website/Nos3DirectoryStructure.html", which does not exist.  I believe it should point to "https://www.stf1.com/NOS3Website/Nos3DirectoryStructureTab.html".

Regards,

  Peter

**Comment by mgrubb-gsfc** [comment]
Good find, we will update this.
