### ISSUE TITLE
NOS time driver failing to launch (fresh NOS3 install)

### ISSUE THREAD

**Issue by smccrossin** [nasa/nos3#399]
I just set up NOS3 per the instructions provided in the README.  Everything looks OK, except that the NOS time driver is failing to launch. The 'make launch' output ends with --
```
NOS Time Driver...
Error response from daemon: No such container: nos_time_driver

Docker launch script completed!
```

I've attached the full terminal output of the session, from 'make clean' to 'make prep' to 'make' and finally 'make launch'.  I've also attached the contents of the terminal's "NOS Time Driver" tab, in case that's useful.

To check whether I'd made some mistake with the install and build, I tried again on a fresh out of the box Windows 11 laptop, taking extreme care to follow each step in the README, in the precise order given.  I got the same result.

42's cam and map displays also do not come up, but I assume that's due to not having the time driver running. 

[NOS3 build and launch.txt](https://github.com/user-attachments/files/17562148/NOS3.build.and.launch.txt)

[NOS time driver tab.txt](https://github.com/user-attachments/files/17562150/NOS.time.driver.tab.txt)

**Comment by smccrossin** [comment]
I also tried wiping out the VM and the clone of the repository and starting again from the beginning, but using the dev branch of the repository instead of main.  That did not resolve the issue.
The VM I'm using (the one set up by 'vagrant up') is labelled "nos3_20231101".

**Comment by Isgaroth-the-Green** [comment]
@smccrossin are you still having the aforementioned issue?
