### ISSUE TITLE
Error in getting Telemetry data from EPS Simulator(CLYDE_EPS)

### ISSUE THREAD

**Issue by jayaramanjay97** [nasa/nos3#48]
I am using nos3 - Version 1.05.00. I am trying to get the electrical power system data of nos3 using COSMOS.
When I set Target as "CLYDE_EPS" and command as "EPS_SEND_HK" in the command sender of COSMOS, I get the telemetry packet. But I am receiving the data only for the first ten times I run the command. After that every time I run it,  no telemetry packet is received.
After the first ten times, there are few warnings in the EPS simulator as shown in the image below.
It would be of great help if someone could help me resolve this issue.

![image](https://user-images.githubusercontent.com/35607787/95951480-1e92bd00-0e14-11eb-8b77-388b45b3b7e4.png)

**Comment by jlucas9** [comment]
Closing issue due to age.
Please create a new issue if this problem remains.

Major updates to apps / sims in the works!
