### ISSUE TITLE
Not receiving telemetry data from the ARDUCAM target

### ISSUE THREAD

**Issue by jayaramanjay97** [nasa/nos3#50]
Hello,
ARDUCAM target has 3 commands:
1.CAM_EXP3_CC
2.CAM_HW_CHECK_CC
3.CAM_NOOP_CC

I cant find anywhere what these commands do. Can someone explain what each command does?
Also none of the commands, send any telemetry packets. Any idea why?

Thanks,
Jay

**Comment by mor1ins** [comment]
I solved the problem.
https://github.com/nasa/nos3/issues/72
