### ISSUE TITLE
run make error 

### ISSUE THREAD

**Issue by GitHubForPP** [nasa/nos3#51]
Hi:
Install according to NOS3_Users_Guide_v1.05.pdf, then load the virtual machine to Virtual Box, enter the parent directory of nos3, run make, and prompt the following error:

CMake Warning at /media/sf_nos3/fsw/psp/CMakeLists.txt:12 (message):
  Unable to find ITC CMake Modules

CMake Error at /media/sf_nos3/fsw/psp/CMakeLists.txt:23 (find_package):
  By not providing "FindNOSENGINE.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "NOSENGINE", but CMake did not find one.

  Could not find a package configuration file provided by "NOSENGINE" with
  any of the following names:

    NOSENGINEConfig.cmake
    nosengine-config.cmake

  Add the installation prefix of "NOSENGINE" to CMAKE_PREFIX_PATH or set
  "NOSENGINE_DIR" to a directory containing one of the above files.  If
  "NOSENGINE" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/media/sf_nos3/fsw/build/cpu1/CMakeFiles/CMakeOutput.log".
CMake Error at cmake/mission_build.cmake:344 (message):
  Failed to configure cpu1
Call Stack (most recent call first):
  CMakeLists.txt:113 (process_arch)

May I ask what could be the cause? We hope to get your help.thanks.

**Comment by markospacetech** [comment]
Hi did you ever find a solution to this? I am experiencing the same issue
