### ISSUE TITLE
Small Readme typos

### ISSUE THREAD

**Issue by jeffstjean** [nasa/nos3#52]
Line 11 and line 64 of the [Readme](https://github.com/nasa/nos3/blob/master/README.md) do not specify the http protocol before the link so Github treats them as relative links (and generate a 404). I didn't want to create a PR for such a small issue but just wanted to let you guys know!

If you would prefer a PR, just let me know.

**Comment by mgrubb-gsfc** [comment]
Thank you, will get that fixed.
