### ISSUE TITLE
Changing the satellite position dynamically through COSMOS

### ISSUE THREAD

**Issue by jayaramanjay97** [nasa/nos3#53]
Is it possible to dynamically change the satellite's position through COSMOS.
Like the Generic wheel simulator can change torque and the direction the satellite rotates, is it possible to change the parameters of satellite from COSMOS?
e.g. To change the altitude of the satellite by sending a command from COSMOS?
Any help would mean a lot.
Thanks
Jay

**Comment by mgrubb-gsfc** [comment]
Jay, 

This is not possible in the current configuration. That would need a thruster added to the satellite model to produce the change in altitude. The functionality of the dynamics simulation is there, but the simulator for the thruster and an application to control it would need written.

You can however change the orbit parameters for the entire simulation to change the altitude when it starts. This can be done through the files in sims/cfg/InOut/Orb_LEO.txt

**Comment by jlucas9** [comment]
Closing issue due to age.
Please create a new issue if this problem remains.
