### ISSUE TITLE
questions about next release (1.06.00)

### ISSUE THREAD

**Issue by ssprowls** [nasa/nos3#59]
Hello,

I was just wondering what the current plans were for a version 1.06.00 release, meaning what that may include, and also an estimated release date, if any.

Thanks!

**Comment by geoleoheo** [comment]
I would also be interested. Thanks!!

**Comment by jlucas9** [comment]
Closing issue due to age.
Please create a new issue if this problem remains.

Very soon! Attempting to move all the internal developments and future work out into the open source community to increase support.
