### ISSUE TITLE
Constellations

### ISSUE THREAD

**Issue by UlrichLouw** [nasa/nos3#68]
I've been wondering whether the simulation can be used to implement satellite constellations?

**Comment by msuder** [comment]
Yes, 42 supports constellations, so NOS3 would as well.  

You could have one satellite in 42 be hooked in to the sims and flight software and COSMOS for the flight software to control/interface with and a number of other satellites just flying in 42... or you could have multiple satellites with 42<->sim<->flight software<->COSMOS connections.  

Refer to https://github.com/ericstoneking/42 for more info on 42 and how it supports multiple satellites (including formation flying).

**Comment by UlrichLouw** [comment]
Thank you @msuder.
