### ISSUE TITLE
Component Architecture

### ISSUE THREAD

**Issue by jlucas9** [nasa/nos3#74]
Update the folder structure to allow components to be stored in a single location and contain the standard information related to that component in one folder / submodule.

**Comment by JiveyGuy** [comment]
This would be very interesting. Can't wait to see where it goes.

**Comment by jlucas9** [comment]
Merged to `dev`!

**Comment by msuder** [comment]
Note that this requires a very specific directory structure and there are some build/run helper things going on.

The directory "components" must live at the top level of the directory structure (beside fsw, gsw, and sims).  Under components can be one or more component subdirectories.  Each of these must have subdirectories:  fsw, gsw, sims.

Building flight software requires the magic of the CFS_APP_PATH variable in the top level Makefile in order for the component flight software to get built.

Building sims depends on the "# Add Component Sims" magic in the sims/CMakeLists.txt file in order for the component sims to get built.

Running COSMOS with cmd/telem definitions for components depends on relative pathing done in gsw/cosmos/config/system/nos3_system.txt to get the definitions, and some magic in gsw/scripts/stop.sh to keep the cmd/telem definitions fresh.
