### ISSUE TITLE
Incomplete installation in Cosmos Gems

### ISSUE THREAD

**Issue by satzguyz** [nasa/nos3#75]
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "gem install cosmos --no-ri --no-rdoc", "delta": "0:00:06.492242", "end": "2022-05-21 13:35:55.518110", "msg": "non-zero return code", "rc": 1, "start": "2022-05-21 13:35:49.025868", "stderr": "ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)\n    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.6-x64-unknown.gemspec.rz)", "stderr_lines": ["ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)", "    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.6-x64-unknown.gemspec.rz)"], "stdout": "", "stdout_lines": []}

**Comment by tmortn77** [comment]
Getting the same
