### ISSUE TITLE
Error 2 received with "make launch" after install of NOS3

### ISSUE THREAD

**Issue by kabarr** [nasa/nos3#79]
I’ve installed NOS3 per the instructions on [GitHub - nasa/nos3](https://github.com/nasa/nos3).  I successfully got through the “Installing” steps (1-8) and started the “Getting Started” steps.  When I reached step 3 (make launch) got an error (2).
I copied the contents of the terminal to a text file (attached).  Is there another way to start NOS3?
[MakeOutput.txt](https://github.com/nasa/nos3/files/9548278/MakeOutput.txt)

**Comment by jlucas9** [comment]
Hi @kabarr,
Could you run the following commands in the terminal inside your NOS3 VM and try to launch again?
```
cd ~/Desktop/github-nos3/gsw/scripts
dos2unix *
cd ~/Desktop/github-nos3
make launch
```

I think that potentially when cloning into your host machine it changed the line endings of the files.  
Thanks and let me know how it goes!

**Comment by kabarr** [comment]
This worked!  Maybe put this solution in FAQs?  Thank you!

From: John P. Lucas ***@***.***>
Sent: Wednesday, September 14, 2022 12:58 PM
To: nasa/nos3 ***@***.***>
Cc: Barr, Kathryn A (MSFC-HP25)[MO&I] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [nasa/nos3] Error 2 received with "make launch" after install of NOS3 (Issue #79)


Hi @kabarr<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkabarr&data=05%7C01%7Ckathryn.a.barr%40nasa.gov%7C44f13c5989664020bcfc08da967a9fe2%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637987750662021764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rs8OO0YPbrx12V%2BHD7iyyGZxHyfGMYCEZ8BTvr52mXc%3D&reserved=0>,
Could you run the following commands in the terminal inside your NOS3 VM and try to launch again?

cd ~/Desktop/github-nos3/gsw/scripts

dos2unix *

cd ~/Desktop/github-nos3

make launch

I think that potentially when cloning into your host machine it changed the line endings of the files.
Thanks and let me know how it goes!

-

**Comment by kabarr** [comment]
Issue resolved with suggested commands to change the line endings.  Thanks !
