### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by jlucas9** [nasa/nos3#82]
Need to capture "component workflow" while doing the general user's guide overhaul in the GitHub Wiki.

https://github.com/nasa/nos3/wiki

Robert B. has experience with this wiki should you run into any issues!

**Comment by msuder** [comment]
The initial GitHub Wiki is complete.  Much information was captured from the NOS3 User Manual and Developer's Guide version 1.05.  This information was double checked, corrected, streamlined, and generally improved.  In addition, information on the NOS3 Components, Repository and Directory Structure was added to describe the new "component workflow".
