### ISSUE TITLE
error during installation cosmos and gem

### ISSUE THREAD

**Issue by refaat100** [nasa/nos3#9]
default: Gem installation...
    default: mkdir: cannot create directory ‘/home/root/Desktop’: No such file or directory
    default: bash: line 7: /home/root/.gemrc: No such file or directory
    default: option --opname is deprecated: support discontinued
    default: invalid options: -SHN
    default: (invalid options are ignored)

**Comment by jlucas9** [comment]
Hi refaat100,
These errors are related to the provisioning script, [specifically here](https://github.com/nasa/nos3/blob/1.03.01/support/installers/ubuntu/nos3_ubuntu_64_FULL_cosmos.sh#L45), and will be address by the next release.  They do not currently affect the installation.  Please follow up if this causes issues for you.  
Thanks and have a great day!
