### ISSUE TITLE
Generic RW Not Starting

### ISSUE THREAD

**Issue by jlucas9** [nasa/nos3#94]
Seems that in the latest `dev` branch 59e8ec6528f0d9220e3776afa90d5026e6e396a8 the generic reaction wheel application fails to start:
```
1958-001-00:00:00.32873 ES Startup: Loading file: /cf/generic_reaction_wheel.so, APP: RW
1958-001-00:00:00.32874 ES Startup: Could not load cFE application file:/cf/generic_reaction_wheel.so. EC = 0xFFFFFF98
```

**Comment by msuder** [comment]
The fix for this issue has been committed to git and verified to have fixed the issue.  This issue is closed.
